server:
  port: 8080

spring:
  #开启AOP
  aop:
    proxy-target-class: true
  # jdbc
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.wofeng.articlemanagement.entity
  mapper-locations: classpath:com/wofeng/articlemanagement/mapper/xml/*.xml

api:
  #图片和视频存放路径
  fileImagePath: D:/nginx-1.13.1/html/
  #netimagePath:
  #domain:

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
